package com.qf.oa.dao;

import com.qf.oa.entity.Role;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated
     */
    Role selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Role record);


    List<Role> queryAll();

    /**
     * 查询所有角色，但是标记出来哪些角色是eid这个职工拥有的
     * @param eid
     * @return
     */
    List<Role> queryAllEid(Integer eid);

    /**
     * 根据eid查询当前拥有的角色
     * @param eid
     * @return
     */
    List<Role> queryByEid(Integer eid);

    int deleteRescByRid(Integer rid);

    int insertRescRidInfo(@Param("rid") Integer rid, @Param("reids") Integer[] reids);
}